export const initialState =
{
    "nft": [
        {
            "id": 1,
            "userId": 'Alice',
            "userAddress": "0x11111",
            "imgURI": "https://drive.google.com/file/d/1Bfqd4Z7v2WafECjtkX5vtVNVn6h2uhDM/view?usp=sharing",
            "price": 10,
            'description': 'The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles.',
            'created_at': '2022y01m01d',
        },
        {
            "id": 2,
            "userId": 'Bab',
            "userAddress": "0x22222",
            "imgURI": "https://drive.google.com/file/d/1FOjmWn6EZUE5fNyig_0XzZiEhRgn0BCI/view?usp=sharing",
            "price": 28,
            'description': 'user is assigned a value but never used',
            'created_at': '2022y01m02d',
        },
        {
            "id": 3,
            "userId": 'Cathy',
            "userAddress": "0x33333",
            "imgURI": "https://drive.google.com/file/d/1vrJkGg-ibndAPcI7kvESKIT_saI4Idhq/view?usp=sharing",
            "price": 321,
            'description': 'web3 is assigned a value but never used',
            'created_at': '2022y01m03d',
        },
        {
            "id": 4,
            "userId": 'Druid',
            "userAddress": "0x4444",
            "imgURI": "https://drive.google.com/file/d/1-2AuiA6e7U9m_1ZCREoUWBe1G0IiOk7F/view?usp=sharing",
            "price": 62,
            'description': 'img elements must have an alt prop, either with meaningful text, or an empty string for decorative images',
            'created_at': '2022y01m04d',
        },
        {
            "id": 5,
            "userId": 'Ella',
            "userAddress": "0x55555",
            "imgURI": "https://drive.google.com/file/d/1omGxo4bQAoge7oYg9rWdXAEwrdjl84Zk/view?usp=sharing",
            "price": 2,
            'description': 'This package is broken and no longer maintained. mkdirp itself supports promises now, please switch to that.',
            'created_at': '2022y01m05d',
        },
        {
            "id": 6,
            "userId": 'franco',
            "userAddress": "0x66666",
            "imgURI": "https://drive.google.com/file/d/1F3OdmjUOzpD-7cBa3kPxxmrB8Pu6e7BU/view?usp=sharing",
            "price": 92,
            'description': 'Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.',
            'created_at': '2022y01m06d',
        },
    ],
}